#!/bin/bash
set -e



case "$1" in
  configure)
    update-alternatives --install /usr/share/plymouth/themes/default.plymouth default.plymouth /usr/share/plymouth/themes/biglinux-logo-antigo/biglinux-logo-antigo.plymouth  100
    sed -i 's|^ *\bTheme\b *=.*|Theme=biglinux-logo-antigo|' /etc/plymouth/plymouthd.conf
    update-initramfs -u
;;

esac
exit 0
